### НАзвания столбцов двигателя для отображения в таблице GUI (на русском языке)
id: ID 
model: Модель двигателя
p_nom: Pном., Вт
m_nom: Mном., Нм
type_id: Тип двигателя
n_nom:  Частота вращения, об/мин
u_nom: Uном., В
i_nom: Iном., А
r_nom: Rя., Ом
j_nom: Момент инерции ротора, кг·м²
m: Масса, г
price: Цена, руб
drawing: Чертеж
company: Компания-производитель

###Названия стобцов редуктора для отображения в таблице GUI (на русском языке)
gear_id: ID
gear_name: Модель редуктора
gear_company: Компания-производитель
gear_type: Тип редуктора
i: Передаточное отношение
speed_norm: Частота вращения на выходе, об/мин
c: Жесткость, Нм/рад
clearance: Люфт, рад
torque_nom: Номинальный момент, Нм
inertial_torque: Момент инерции, кг·м²
mass: Масса, г
price: Цена, руб
drawing: Чертежs
efficiency: КПД

### Названия стобцов энкодера для отображения в таблице GUI (на русском языке)
id_encoder: ID
encoder_name: Модель энкодера
id_company: Компания-производитель
id_type_encoder: Тип энкодера
shaft_diameter: Диаметр вала, мм
rotor_breakway_torque: Момент ротора, Нм
rotor_momoent_of_inertia: Момент инерции ротора, кг·м²
maximum_rotation_speed: Максимальная частота вращения, об/мин
supply_voltage: Напряжение питания, В
lines_count: Разрешающая способность
weight: Масса, г
drawing: Чертеж
price: Цена, руб 